# Generated by Django 4.1.5 on 2023-05-24 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assetsData", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift_History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("From_Location", models.CharField(max_length=200)),
                ("To_Location", models.CharField(max_length=200)),
                ("Date", models.DateField(auto_now=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "from_User",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_from_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_User",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_to_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_No", models.CharField(max_length=500)),
                ("Date_Of_Entry", models.DateField()),
                ("Date_Of_Invoice", models.DateField()),
                ("Rate", models.CharField(max_length=200)),
                ("Discount", models.CharField(max_length=100)),
                ("Tax", models.CharField(max_length=100)),
                ("Ammount", models.CharField(max_length=1000)),
                ("make", models.CharField(blank=True, max_length=500, null=True)),
                ("sno", models.CharField(blank=True, max_length=500, null=True)),
                ("Item_Code", models.CharField(max_length=200)),
                ("Final_Code", models.CharField(blank=True, max_length=500, null=True)),
                ("remark", models.TextField(blank=True, null=True)),
                ("Is_Dump", models.BooleanField(default=False)),
                ("isIssued", models.BooleanField(default=False)),
                (
                    "Financial_Year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assetsData.finantial_year",
                    ),
                ),
                (
                    "Location_Code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assetsData.location_description",
                    ),
                ),
                (
                    "Purchase_Item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assetsData.asset_type",
                    ),
                ),
                (
                    "Shift_History",
                    models.ManyToManyField(blank=True, to="store.shift_history"),
                ),
                (
                    "Vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assetsData.vendor",
                    ),
                ),
                (
                    "buy_for",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assetsData.departments",
                    ),
                ),
                (
                    "stock_register",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assetsData.stock_register",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dump",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Dump_Date", models.DateField()),
                ("Remark", models.TextField(blank=True, null=True)),
                ("Is_Sold", models.BooleanField(default=False)),
                ("Date_Of_Sold", models.DateField(blank=True, null=True)),
                ("Sold_Price", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "Item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.ledger"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="assign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickedUp", models.BooleanField(default=False)),
                ("assigned_to_pickup", models.CharField(max_length=100)),
                ("assigned_person", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.ledger"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
