# Generated by Django 4.1.5 on 2023-05-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assign",
            name="pickupDate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
