# Generated by Django 4.1.5 on 2023-05-26 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0002_assign_pickupdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="complaints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("store_replied", models.BooleanField(default=False)),
                ("store_comment", models.TextField(null=True)),
                ("complaint_status", models.CharField(max_length=40, null=True)),
                ("time_registered", models.DateTimeField(auto_now_add=True, null=True)),
                ("time_closed", models.DateTimeField(null=True)),
                (
                    "complaint_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.assign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
