# Generated by Django 4.1.5 on 2023-07-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assetsData", "0003_delete_complaints"),
        ("store", "0003_complaints"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="current_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="new_department",
                to="assetsData.departments",
            ),
        ),
    ]
