# Generated by Django 4.1.5 on 2023-05-26 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assetsData", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="assetsData.location_description",
            ),
        ),
    ]
