# Generated by Django 4.1.5 on 2023-05-26 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assetsData", "0002_profile_location"),
    ]

    operations = [
        migrations.DeleteModel(
            name="complaints",
        ),
    ]
